// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTm2xSI0gycHa8Euly41ZmrXTckl-V3qw',
    appId: '1:1065212238714:web:c56c0d769206e3954714c3',
    messagingSenderId: '1065212238714',
    projectId: 'chat-app-he',
    authDomain: 'chat-app-he.firebaseapp.com',
    storageBucket: 'chat-app-he.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK46MoxGvBnxSa71pTjrfiqPHeeDH4M4s',
    appId: '1:1065212238714:android:3ff8dd2c05e20ba94714c3',
    messagingSenderId: '1065212238714',
    projectId: 'chat-app-he',
    storageBucket: 'chat-app-he.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDACU34UA1UZV_CknuGg9Zqrc_3hGMFSEs',
    appId: '1:1065212238714:ios:1e27fdf13892cf564714c3',
    messagingSenderId: '1065212238714',
    projectId: 'chat-app-he',
    storageBucket: 'chat-app-he.appspot.com',
    iosClientId: '1065212238714-abt8e79t99f6vpi4qllj9abpcb789c3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.messangerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDACU34UA1UZV_CknuGg9Zqrc_3hGMFSEs',
    appId: '1:1065212238714:ios:96ebf8f7a6f8f12c4714c3',
    messagingSenderId: '1065212238714',
    projectId: 'chat-app-he',
    storageBucket: 'chat-app-he.appspot.com',
    iosClientId: '1065212238714-aueol9hdf1creqpi3hiahn7r3adgonm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.messangerApp.RunnerTests',
  );
}
